In [7]:
import numpy
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence
import keras.backend as K

In [9]:
# fix random seed for reproducibility
numpy.random.seed(7)

with open('X_train.npy', 'r') as f:
    X_train = numpy.load(f)

with open('y_train.npy', 'r') as f:
    y_train = numpy.load(f)

with open('X_test.npy', 'r') as f:
    X_test = numpy.load(f)

with open('y_test.npy', 'r') as f:
    y_test = numpy.load(f)

# truncate and pad input sequences
max_review_length = 500
X_train = sequence.pad_sequences(X_train, maxlen=max_review_length)
X_test = sequence.pad_sequences(X_test, maxlen=max_review_length)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte

In [7]:
# create the model
top_words = 5000
embedding_vecor_length = 32
model = Sequential()
model.add(Embedding(top_words, embedding_vecor_length, input_length=max_review_length))
model.add(LSTM(100, return_sequences = False))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 500, 32)           160000    
_________________________________________________________________
lstm_2 (LSTM)                (None, 100)               53200     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 101       
Total params: 213,301
Trainable params: 213,301
Non-trainable params: 0
_________________________________________________________________
None


In [3]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=3, batch_size=64)

TypeError: 'str' object is not callable

In [4]:
import sys
!{sys.executable} -m pip install tensorflow

    100% |████████████████████████████████| 43.7MB 39kB/s eta 0:00:011
    100% |████████████████████████████████| 1.2MB 1.1MB/s ta 0:00:01
  Using cached wheel-0.30.0-py2.py3-none-any.whl
    100% |████████████████████████████████| 81kB 4.7MB/s ta 0:00:011
    100% |████████████████████████████████| 1.7MB 914kB/s ta 0:00:01
    100% |████████████████████████████████| 3.1MB 498kB/s ta 0:00:011
  Using cached Werkzeug-0.14.1-py2.py3-none-any.whl
  Using cached bleach-1.5.0-py2.py3-none-any.whl
  Using cached Markdown-2.6.11-py2.py3-none-any.whl
  Using cached html5lib-0.9999999.tar.gz
  Running setup.py install for gast ... - \ done
  Running setup.py install for absl-py ... - \ done
  Running setup.py install for termcolor ... - \ done
  Running setup.py install for html5lib ... - \ | done
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [36]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM
from numpy import array
# define model
inputs1 = Input(shape=(3, 45))
lstm1, state_h, state_c = LSTM(11, return_sequences=True, return_state=True)(inputs1)
model = Model(inputs=inputs1, outputs=[lstm1, state_h, state_c])
# define input data
data = numpy.zeros((3, 45)).reshape((-1,3,45))
# make and show prediction

In [99]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM
from numpy import array
# define model
inputs1 = Input(shape=(3, 45))
lstm1 = LSTM(11, return_sequences=False, return_state=False)(inputs1)
model = Model(inputs=inputs1, outputs=[lstm1])
# define input data
data = numpy.zeros((3, 45)).reshape((-1,3,45))
# make and show prediction

In [102]:
model.layers[1].output

<tf.Tensor 'lstm_25/TensorArrayReadV3:0' shape=(?, 11) dtype=float32>

In [103]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         (None, 3, 45)             0         
_________________________________________________________________
lstm_25 (LSTM)               (None, 11)                2508      
Total params: 2,508
Trainable params: 2,508
Non-trainable params: 0
_________________________________________________________________


In [53]:
w = model.layers[1].get_weights()

In [56]:
w[0].shape

(45, 44)

In [57]:
w[1].shape

(11, 44)

In [58]:
w[2].shape

(44,)

In [47]:
2508/4/11

57.0

In [38]:
model.predict(data)

[array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]], dtype=float32),
 array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32),
 array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)]

In [20]:
inputs1

<tf.Tensor 'input_3:0' shape=(?, 3, 45) dtype=float32>

In [23]:
lstm1

<tf.Tensor 'lstm_3/transpose_1:0' shape=(?, ?, 11) dtype=float32>

In [21]:
state_h

<tf.Tensor 'lstm_3/while/Exit_2:0' shape=(?, 11) dtype=float32>

In [22]:
state_c

<tf.Tensor 'lstm_3/while/Exit_3:0' shape=(?, 11) dtype=float32>

In [ ]:
# LSTM for sequence classification in the IMDB dataset
import numpy
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence
# fix random seed for reproducibility
numpy.random.seed(7)
# load the dataset but only keep the top n words, zero the rest
top_words = 5000
(X_train, y_train), (X_test, y_test) = imdb.load_data(nb_words=top_words)
# truncate and pad input sequences
max_review_length = 500
X_train = sequence.pad_sequences(X_train, maxlen=max_review_length)
X_test = sequence.pad_sequences(X_test, maxlen=max_review_length)

In [80]:
# create the model
embedding_vecor_length = 32
model = Sequential()
model.add(Embedding(1, embedding_vecor_length, input_length=max_review_length))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_10 (Embedding)     (None, 500, 32)           32        
_________________________________________________________________
lstm_15 (LSTM)               (None, 100)               53200     
_________________________________________________________________
dense_10 (Dense)             (None, 1)                 101       
Total params: 53,333
Trainable params: 53,333
Non-trainable params: 0
_________________________________________________________________
None


In [83]:
w = model.layers[0].get_weights()

In [85]:
print(w[0].shape)

(1, 32)


In [88]:
# create the model
embedding_vecor_length = 32
model = Sequential()
model.add(Embedding(5000, embedding_vecor_length, input_length=max_review_length))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_11 (Embedding)     (None, 500, 32)           160000    
_________________________________________________________________
lstm_16 (LSTM)               (None, 100)               53200     
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 101       
Total params: 213,301
Trainable params: 213,301
Non-trainable params: 0
_________________________________________________________________
None


In [98]:
# create the model
embedding_vecor_length = 32
model = Sequential()
model.add(Embedding(5000, 32, input_length=61))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_19 (Embedding)     (None, 61, 32)            160000    
_________________________________________________________________
lstm_24 (LSTM)               (None, 100)               53200     
_________________________________________________________________
dense_19 (Dense)             (None, 1)                 101       
Total params: 213,301
Trainable params: 213,301
Non-trainable params: 0
_________________________________________________________________
None


In [89]:
w = model.layers[0].get_weights()

In [90]:
print(w[0].shape)

print(w[1].shape)

print(w[2].shape)

(5000, 32)


IndexError: list index out of range

In [64]:
len(w)

3

In [25]:
model.fit(X_train, y_train, nb_epoch=3, batch_size=64)
# Final evaluation of the model
scores = model.evaluate(X_test, y_test, verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/keras/datasets/imdb.py:49: UserWarning: The `nb_words` argument in `load_data` has been renamed `num_words`.
  warnings.warn('The `nb_words` argument in `load_data` '


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 500, 32)           160000    
_________________________________________________________________
lstm_4 (LSTM)                (None, 100)               53200     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 101       
Total params: 213,301
Trainable params: 213,301
Non-trainable params: 0
_________________________________________________________________
None


/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/keras/models.py:942: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/3
25000/25000 [==============================] - 189s 8ms/step - loss: 0.4432 - acc: 0.7914

In [27]:
X_test.shape

(25000, 500)

In [29]:
X_test[12].reshape((1,-1))

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    1,  449, 3214,  449, 3214,   12,   66,  214,
          23,   61,    2,   54,    6,  364,  352, 1149,  189, 1586,  497,
           8,  168,  221,   11,    4,  898,   34,  260,    6,  762,    7,
          52, 1433, 1719,   56,   11,    4,  177,   64,    8, 4337,  257,
          31,   11,    4,    2,   91, 

In [32]:
model.predict(X_test[9].reshape((1,-1)))

array([[0.7964928]], dtype=float32)